apiVersion: bindplane.observiq.com/v1
kind: Configuration
metadata:
    name: benchmark
    description: benchmark
    labels:
        agent-type: observiq-otel-collector
        platform: linux
spec:
    contentType: ""
    measurementInterval: ""
    topologyInterval: ""
    disableLegacyEnvVarNormalization: false
    sources:
        - id: 01KFWXEAMFFHNR3NZ18R4WQZYY
          displayName: http_listen
          type: http
          parameters:
            - name: listen_address
              value: 0.0.0.0
            - name: http_port
              value: 7075
            - name: path
              value: ""
            - name: enable_listen_tls
              value: false
            - name: listen_tls_key_file
              value: ""
            - name: listen_tls_cert_file
              value: ""
            - name: raw_logs
              value: true
          processors:
            - id: 01KJFPXS0FXPTG3VCDKJFC9RWZ
              displayName: Extract PII to Attributes
              type: transform:1
              parameters:
                - name: telemetry_type
                  value: Logs
                - name: statements
                  value:
                    - merge_maps(body, ParseJSON(body), "upsert") where IsMap(body) and true
                    - set(body, ParseJSON(body)) where not IsMap(body) and true
                    - set(cache["copy_field"], body["pii"]) where body["pii"] != nil
                    - merge_maps(attributes, cache["copy_field"], "upsert") where cache["copy_field"] != nil
                - name: conditions
                  value: []
                - name: error_mode
                  value: ignore
                - name: logs_context
                  value: log
                - name: metrics_context
                  value: datapoint
                - name: traces_context
                  value: span
            - id: 01KG4CFMPQW972NZ9M00B051XG
              type: filter-by-condition
              parameters:
                - name: telemetry_types
                  value:
                    - Logs
                    - Metrics
                    - Traces
                - name: action
                  value: exclude
                - name: condition
                  value:
                    ottl: attributes["color"] == "Green"
                    ui:
                        operator: ""
                        statements:
                            - key: color
                              match: attributes
                              operator: Equals
                              value: Green
          routes: {}
    destinations:
        - id: 01KFXCH53W5CFVQZFHF6RVV2TF
          name: s3_dest
          processors:
            - id: 01KFXCJG1BY6WDZKHJ5MR1KYF4
              displayName: sample
              type: sampling
              parameters:
                - name: condition
                  value: ""
                - name: drop_ratio
                  value: "0.95"
            - id: 01KFXJ2EZN1HAT4M2BNT9TFPHY
              displayName: Batch for AWS S3
              type: batch
              parameters:
                - name: send_batch_size
                  value: 8192
                - name: send_batch_max_size
                  value: 8192
                - name: timeout
                  value: 30s
              recommendation: aws_s3_batch
    selector:
        matchLabels:
            configuration: benchmark
---
apiVersion: bindplane.observiq.com/v1
kind: Destination
metadata:
    name: s3_dest
spec:
    type: aws_s3
    parameters:
        - name: telemetry_types
          value:
            - Logs
        - name: region
          value: us-west-2
        - name: bucket
          value: '{S3_PLACEHOLDER}'
        - name: prefix
          value: bindplane
        - name: file_prefix
          value: ""
        - name: partition
          value: minute
        - name: partition_format
          value: year=%Y/month=%m/day=%d/hour=%H/minute=%M
        - name: compression
          value: gzip
        - name: storage_class
          value: STANDARD
        - name: endpoint
          value: ""
        - name: drop_raw_copy
          value: false
        - name: logs_marshaler
          value: otlp_json
        - name: metrics_marshaler
          value: otlp_json
        - name: traces_marshaler
          value: otlp_json
        - name: resource_to_prefix
          value: com.awss3.prefix
        - name: timeout
          value: 30
        - name: retry_mode
          value: standard
        - name: retry_max_attempts
          value: 3
        - name: retry_max_backoff
          value: 20
        - name: sending_queue_enabled
          value: false
        - name: sending_queue_num_consumers
          value: 10
        - name: sending_queue_queue_size
          value: 5000
        - name: sending_queue_wait_for_result
          value: false
        - name: sending_queue_block_on_overflow
          value: false
        - name: persistent_queue_enabled
          value: true
        - name: persistent_queue_storage_extension
          value:
            parameters:
                - name: persistent_queue_directory
                  value: ${OIQ_OTEL_COLLECTOR_HOME}/storage
                - name: timeout
                  value: 1
                - name: persistent_queue_fsync
                  value: true
            type: file_storage_persistent_queue
