input {
  http {
    host => "0.0.0.0"
    port => 2085
    codec => json
    ecs_compatibility => "disabled"
  }
}

filter { }

output {
  s3 {
    region => "us-west-2"
    bucket => "{S3_PLACEHOLDER}"
    prefix => "logstash/"
    time_file => 1
    codec => json_lines
  }
}
